### ISSUE TITLE
License infringement in 'le' text editor.

### ISSUE THREAD

**Issue by MiguelVis** [lindehaven/CP-M#1]
Hello.

I'm very surprised you have written your 'le' text editor borrowing a lot of code from my 'te' text editor without respecting the GPL 'te' license and publishing 'le' under another -incompatible- license.

I will not detail here all the coincidences between my code and yours (they are a lot!), but the following will serve as an example:

Your code:

```
/* Move cursor one page down */
pageDown() {
    int first, last, to;

    first = edGetFirstLineNumber();
    last = edGetLastLineNumber();
    if (last < lp_tot - 1) {
        to = first + ED_ROWS;
        if (to >= lp_tot)
            to = lp_tot - 1;
        lp_cur = to; ed_row = ed_col = 0;
        edUpdAll();
    } else
        toEOF();
}
```

My code:

```
/* Page down
   ---------
*/
LoopPgDown()
{
	int first, last, to;

	first = LoopFirst();
	last = LoopLast();

	if(last < lp_now - 1)
	{
		to = first + box_rows;

		if(to >= lp_now)
			to = lp_now - 1;

		lp_cur = to; box_shr = box_shc = 0;

		RefreshAll();
	}
	else
		LoopBottom();
}
```

My 'te' text editor is licensed under the GNU GENERAL PUBLIC LICENSE v2 as stated in the code and in a separate text file:

> This program is free software; you can redistribute it and/or modify it
> under the terms of the GNU General Public License as published by the
> Free Software Foundation; either version 2, or (at your option) any
> later version.

According to the license, you can modify the code and distribute it, but you must follow the license rules, including:

> 2. **You may modify** your copy or copies of the Program or any portion
> of it, thus forming a work based on the Program, **and copy and
> distribute such modifications** or work under the terms of Section 1
> above, **provided that you also meet all of these conditions**:
> 
>     a) You must cause the modified files to carry prominent notices
>     stating that you changed the files and the date of any change.
> 
>     b) You must cause any work that you distribute or publish, that in
>     whole or in part contains or is derived from the Program or any
>     part thereof, **to be licensed as a whole** at no charge to all third
>     parties **under the terms of this License**.
> 
>     c) If the modified program normally reads commands interactively
>     when run, you must cause it, when started running for such
>     interactive use in the most ordinary way, to print or display an
>     announcement **including an appropriate copyright notice** and a
>     notice that there is no warranty (or else, saying that you provide
>     a warranty) and that users may redistribute the program under
>     these conditions, and telling the user how to view a copy of this
>     License.  (Exception: if the Program itself is interactive but
>     does not normally print such an announcement, your work based on
>     the Program is not required to print an announcement.)

I formally ask you to follow the 'te' license rules and modify your code, copyright and license accordingly.

**Comment by lindehaven** [comment]
Hello MiguelVis,
It is true that I borrowed lots of code from your te editor. I missed out to include the GPL license and credits to you before I pushed to GitHub. It was my mistake and I will rectify that as soon as possible. I sincerely apologize.

**Comment by lindehaven** [comment]
Added copyright and GPL license in 'le.c', 'le.h' and 'copying.txt'. Removed previous incorrect license.

**Comment by MiguelVis** [comment]
Thanks for your prompt reply and solution.

**Comment by lindehaven** [comment]
Thank you for pointing out my mistake.
